// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egkwwdkbjkndweickffn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVna3d3ZGtiamtuZHdlaWNrZmZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTIwMDUsImV4cCI6MjA2ODM4ODAwNX0.wvMaep5fhZbZe3mPO3V1F7fTWUI6wV5M04z6Uk0F4Xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});